# Header
menu:
  首页: / || fas fa-home
  归档: /archives || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  生活: /life/ || fas fa-heartbeat

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# 代码样式
highlight_theme: mac
# 代码是否可复制
highlight_copy: true
# 代码是否展开
highlight_shrink: false
# 代码自动换行
code_word_wrap: true

social:
  fab fa-github: https://github.com/xxxxx || Github
  fas fa-envelope: mailto:vegetasuper@163.com || Email

readmode: true
